# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/basys3_xdc.xdc

# IP: ip/frame_buffer/frame_buffer.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frame_buffer || ORIG_REF_NAME==frame_buffer} -quiet] -quiet
